# Generated by Django 5.0.3 on 2024-03-31 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(
                        message="Invalid email format."
                    )
                ],
            ),
        ),
    ]
